/**
 * OpenAPI Generated Types
 *
 * This file is auto-generated by openapi-typescript.
 * Run `pnpm --filter @taboot/api-client generate:types` to regenerate.
 *
 * NOTE: This is a placeholder. Generate actual types by running:
 * 1. Start FastAPI: docker compose up taboot-app
 * 2. Generate types: pnpm --filter @taboot/api-client generate:types
 */

// Placeholder type - replace with generated types
export interface paths {}

export interface components {
  schemas: {};
}
