[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "taboot-schemas"
version = "0.4.0"
description = "Taboot Pydantic models and OpenAPI schemas"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Jacob Magar", email = "jmagar@gmail.com" }]
license = { text = "Proprietary" }

dependencies = [
  "pydantic>=2.12.0,<3",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.4.2",
]

[tool.hatch.build.targets.wheel]
packages = ["taboot_schemas"]
