repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff Format
        entry: uv run ruff format
        language: system
        types_or: [python, pyi]
        pass_filenames: true
      - id: ruff-lint
        name: Ruff Lint
        entry: uv run ruff check
        language: system
        types_or: [python, pyi]
        pass_filenames: true
      - id: mypy
        name: Mypy
        entry: uv run mypy
        language: system
        types_or: [python, pyi]
        pass_filenames: true
