[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "taboot-ingest"
version = "0.4.0"
description = "Taboot ingestion adapters (Firecrawl, normalizer, chunker)"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Jacob Magar", email = "jmagar@gmail.com" }]
license = { text = "Proprietary" }

dependencies = [
  "firecrawl-py>=4.4.0",
  "pydantic>=2.12.0",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.4.2",
  "pytest-asyncio>=1.2.0",
]

[tool.hatch.build.targets.wheel]
packages = ["taboot_ingest"]
