[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "taboot-common"
version = "0.4.0"
description = "Taboot common utilities (logging, config, tracing)"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Jacob Magar", email = "jmagar@gmail.com" }]
license = { text = "Proprietary" }

dependencies = [
  "pydantic>=2.12.0",
  "python-json-logger>=4.0.0",
  "python-dotenv>=1.1.1",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.4.2",
]

[tool.hatch.build.targets.wheel]
packages = ["taboot_common"]
