from typing import Any, ContextManager


class connection:
    def cursor(self, *args: Any, **kwargs: Any) -> ContextManager[Any]: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
