from typing import Any


class SimpleConnectionPool:
    def __init__(self, minconn: int, maxconn: int, *args: Any, **kwargs: Any) -> None: ...
    def getconn(self) -> Any: ...
    def putconn(self, conn: Any) -> None: ...
    def closeall(self) -> None: ...


class ThreadedConnectionPool(SimpleConnectionPool):
    ...


Error = Exception
