[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "taboot-graph"
version = "0.4.0"
description = "Taboot Neo4j driver, Cypher builders, bulk writers"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Jacob Magar", email = "jmagar@gmail.com" }]
license = { text = "Proprietary" }

dependencies = [
  "neo4j>=5.26.0,<6",
  "pydantic>=2.12.0,<3",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.4.2",
  "pytest-asyncio>=1.2.0",
]

[tool.hatch.build.targets.wheel]
packages = ["taboot_graph"]
