[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "taboot-extraction"
version = "0.4.0"
description = "Taboot multi-tier extraction engine (regex, spaCy, LLM)"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Jacob Magar", email = "jmagar@gmail.com" }]
license = { text = "Proprietary" }

dependencies = [
  "spacy>=3.8.1,<4",
  "pyahocorasick>=2.0.0,<3",
  "transformers>=4.44.0,<5",
  "torch>=2.4.0,<3",
  "pydantic>=2.12.0,<3",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.4.2",
  "pytest-asyncio>=1.2.0",
]

[tool.hatch.build.targets.wheel]
packages = ["taboot_extraction"]
